// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { main } from '../models';

export function ConnectSSH(arg1: main.ConnectRequest): Promise<main.ConnectResponse>;

export function GetStatus(): Promise<boolean>;

export function TestConnection(arg1: main.ConnectRequest): Promise<main.TestConnectionResult>;

export function LoadSettings(): Promise<main.AppSettings>;

export function SaveSettings(arg1: main.AppSettings): Promise<boolean>;

export function Disconnect(): Promise<boolean>;

export function StartForward(arg1: string, arg2: string): Promise<string>;

export function StopForward(arg1: string): Promise<boolean>;

export function GetMetrics(): Promise<main.Metrics>;
