// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSSH(arg1) {
  return window['go']['main']['App']['ConnectSSH'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function StartForward(arg1, arg2) {
  return window['go']['main']['App']['StartForward'](arg1, arg2);
}

export function StopForward(arg1) {
  return window['go']['main']['App']['StopForward'](arg1);
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}
